## Invoice [/invoice]

### Invoice [GET]

+ Response 200 (application/json)
        
        {
            "message" : "here is your Invoice ",
            "cart_id" : "cart_id",
            "voucher" : "voucher name",
            "payment" : ""
            "item list" :
            [
               {
                    "item" : "ayam fillet",
                    "quantity" : "10",
               },
               {
                    "item" : "ayam utuh",
                    "quantity" : "7",
               },
               
            ],
            "total_quanity" : 17,
            "total_price" : 70000,
            "tax" : "20%"
            "fixed price": 56000
        }